# Generated by Django 5.2.1 on 2025-06-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_mensagemcontato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('foto', models.ImageField(upload_to='produtos_fotos/')),
                ('historia', models.TextField(blank=True, null=True)),
                ('aplicacao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
